name: First CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a simple command
        env:
          APP_ENV: dev
        run: echo "Building the app in $APP_ENV"

  test:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a simple command
        env:
          BUILD_TYPE: test
        run: echo "Running tests in $BUILD_TYPE"


